sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
addons:
  apt:
    packages:
      - google-chrome-stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - npm run link-packages
script:
  - npm run test
  - npm run test:e2e
cache:
  directories:
    - node_modules
