sudo: required
dist: trusty
language: node_js
node_js:
  - "10"
notifications:
  email:
    - ibmziyi0220@gmail.com
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - gem install chromedriver-helper -v 1.2.0
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - chromedriver-update 73.0.3683.68
  - npm run start:dev &
install:
  - npm run ready
script:
  - npm run test
  - npm run test:e2e
cache:
  directories:
    - node_modules
branches:
  only:
    - master
