language: node_js
node_js:
  - "iojs"
  - "8"
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
install:
  - npm run link-packages
script:
  - npm run test
  - npm run test:e2e
