sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
addons:
  chrome: stable
install:
  - npm run link-packages
before_script:
  - npm run start:dev
script:
  - npm run test
  - npm run test:e2e
cache:
  directories:
    - node_modules
