sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - npm run start:dev &
install:
  - npm run link-packages
script:
  - npm run test
  - npm run test:e2e
cache:
  directories:
    - node_modules
